defaults: &defaults
    # Required.
    api_key: '2b90dedca0019da4dcd52c9ad1e1ac6c'
    secret_key: 'd2931530257d894f434ac12a91186d3d'

    # Optional for Facebook Connect.
    # canvas_page_name: YOUR_APP_CANVAS_NAME
    # Optional for Facebook Connect. Depends on your Facebook App settings.
    # callback_url: http://localhost:3000

    # Optional options.
    # pretty_errors: true
    # set_asset_host_to_callback_url: false
    # tunnel:
    #   public_host_username:
    #   public_host:
    #   public_port: 4007
    #   local_port: 3000

development:
    api_key: 61dca75f6feadf0f9dc17e5c4546e965
    secret_key: ab8bebc09bb68ea69fd96c028745ee3a

test: &test
    api_key: 61dca75f6feadf0f9dc17e5c4546e965
    secret_key: ab8bebc09bb68ea69fd96c028745ee3a

production: &production
  <<: *defaults

# staging:
#   <<: *production
#
# cucumber:
#   <<: *test
